#!/bin/bash
set -x #echo on

cd app
dotnet clean
rm -rf obj
rm -rf bin
cd ..

cd api
dotnet clean
rm -rf obj
rm -rf bin
cd ..

cd common
dotnet clean
rm -rf obj
rm -rf bin
cd ..

cd common
dotnet build
cd ..

cd app
dotnet build
cd ..

cd api
dotnet build
cd ..
